- code/modules/reagents/reagent_containers/glass.dm
If plasma is spilled from a bottle or glass it alerts admins that it was
spilled and gives coordinates.
> Alerts admins/logs when plasma is spilled

- config/game_options.txt
http://www.llagaming.net/forums/threads/heads-and-security-non-antags-feedback.3251/
IN THE EVENT THAT THE THREAD DECIDES WE DO/DONT WANT IT.
> Enabled Sec/captain can be antag

- code/game/objects/items/devices/Thinktronic/Laptop_UI.dm
- code/game/objects/items/devices/Thinktronic/programs/taskmanager.dm
- code/game/objects/items/devices/Thinktronic/tablet_AI_UI.dm
- code/game/objects/items/devices/Thinktronic/tablet_UI.dm
- code/game/objects/items/devices/Thinktronic/tablet_pAI_UI.dm
- code/game/objects/items/devices/Thinktronic/thinktronic.dm
hotfixes:
-spam check on sending files (added)
-task manager sending alerts to self (fixed)
-messaging a null client breaks it (fixed)
-view old logs without the other user existing (fixed)
> Tablet hotfixes

- code/game/objects/items/devices/Thinktronic/Laptop_UI.dm
- code/game/objects/items/devices/Thinktronic/Programing.dm
- code/game/objects/items/devices/Thinktronic/tablet_AI_UI.dm
- code/game/objects/items/devices/Thinktronic/tablet_UI.dm
- code/game/objects/items/devices/Thinktronic/tablet_pAI_UI.dm
> Improved tablets/laptops, you can have multiple ones open at the same time

- code/modules/mob/new_player/new_player.dm
- html/changelog.html
Fixed AI not announcing new arrivals + changelog
> Fixed AI not announcing new arrivals

- code/game/objects/items/devices/Thinktronic/Harddrive.dm
Gave lawyers "Brig Control" app.
> Gave lawyers "Brig Control" app.

- _maps/map_files/tgstation.2.1.3.dmm
- code/game/machinery/suit_storage_unit.dm
- html/changelog.html
Adds medical hardsuit to the CMO's office
> Adds medical hardsuit to the CMO's office

- code/game/objects/items/devices/scanners.dm
- code/modules/reagents/Chemistry-Reagents.dm
Implemented functionality for the Advanced Mass Spectrometer to detect if blood is from a changeling.
Added an entry to the "data" list for blood reagent to prevent destruction of source mob breaking the detection.
> Changeling Test Implemented

- code/game/machinery/suit_storage_unit.dm
> Put the CMO hardsuit in the CMO suit storage.

- code/modules/spacelaw/permabrig_monitor.dm
per DZ, i am allowed to merge my own PR, which i will do now
> Fixed Permadoors access + locking at round start

- .gitignore
With this: If someone compiles there logs and saved wont be merged into
the git.
> Added player_saves, logs, and investigate logs to .gitignore

- code/game/objects/items/weapons/tanks/watertank.dm
See https://github.com/Spoffy/LLA-Station-13/issues/68
> Fixed the water mister bug

- html/changelog.html
IMvader updated:
Wine will now deconvert in the same way and quantity as holy water.
Reduced the numbers required to convert crew members from 3 to 2.
Wine can be cleansed from body (and converted to unholy water) by cultists in the same way as holy water.
FlavoredCactus updated:
Animations added to attacks, being tased, and lack of gravity
Reverted permabrig doors to vanilla settings (No airlock control,bolts)
QuantumWings updated:
Fixed a bug where some misters could be placed in the backpack
Drache updated:
Re-added Virtual Reality
> Changelog 2/2/2015

- code/modules/reagents/Chemistry-Documentation.dm
- code/modules/reagents/Chemistry-Recipes.dm
- tgstation.dme
-Created a dynamic chem manual of all reactions, filtered by category.
-Implemented categories for reactions
-Implemented sorting algorithm for this specific object to sort them alphabetically.
-The Complete Guide to Reactions generates its content at creation. This will typically be roundstart.
> Implemented Dynamic Chemistry Manual

- code/modules/reagents/Chemistry-Documentation.dm
additionally
-removed unnecesary href link in chem book
<THESE STILL NEED TO BE ADDED TO THE MAP>
> Adds Drink mix book using raptor's chembook

- code/modules/mob/living/living.dm
Fixes issue with indefinite floating bodies
> Prevents resting/dead/critical/sleeping bodies from floating

- code/game/objects/items/weapons/melee/misc.dm
cooldown raised to 5 ticks instead of 4
during cooldown can only disarm/attempt to disarm (80% chance to disarm,
20% to fail)
out of cooldown, can 45% chance to knock down, 35% chance to disarm 20%
chance to fail disarm
> Nerfed Telebaton

- code/game/machinery/computer/prisoner.dm
- code/modules/spacelaw/spacelaw.dm
- code/modules/spacelaw/spacelaw_book.dm
-Restricted sentences which may be sent to labor camp.
-To qualify, a sentence must total 500 or more points.
-Added a nice buzzing noise (used one of the mulebots's) and error for the user if it is less than 500.
-Error plays when attempting to remove a card with more than 0 but less than 500 as the goal.
> Restricted Labor Camp Sentences

- code/datums/mind.dm
- code/game/gamemodes/revolution/revolution.dm
- code/game/objects/items/devices/flash.dm
Too many times have i seen deconverted revs "forget" who flashed them.
Example image
> During revolutions, Be told who converted you when deconverted

- code/modules/clothing/gloves/miscellaneous.dm
Added just two lines into captain gloves code, give them the yellow gloves properties.
> Captain gloves insulated.

- code/modules/projectiles/ammunition/energy.dm
Changed to "taser2.ogg" instead of "taser.ogg".
> Disabler shot sound.

- code/modules/clothing/head/helmet.dm
- code/modules/clothing/under/miscellaneous.dm
Made the gladiator armor equal to the roman one.
> Gladiator armor equaled to Roman armor.

- code/game/machinery/computer/shuttle.dm
stops people from constantly spamming the emergency shuttle
you cant spam click the authorize button and it wont announce authorization if you already authorized.
> "ATTENTION" shuttle spam fix

- code/modules/mob/living/living.dm
- code/modules/projectiles/projectile/energy.dm
Hit sound for electrode reverted to "sparks"
No jitter on electrodes
fixed gravity issues with AI
fixed gravity issues with bodies unable to stop jittering after gravity
> Animations fixs and removals

- code/game/objects/items/devices/Thinktronic/thinktronic.dm
Fixs tablet lights being stuck to player
> Fixs tablet lights being stuck to player

- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/debug.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/pai/software.dm
-Comments out pAI's PDA
-Adds "Become pAI" debug verb (Debug tab, need coder rank to access)
> Comments out pAI's PDA ; Adds "Become pAI" debug verb

- code/game/machinery/computer/crew.dm
Crew Monitor computer now tracks jumpsuits in asteroid z-level too.
> Asteroid Suit Sensors

- code/modules/events/ninja.dm
> When the ninja suit terminates, end the ntick proc

- code/game/machinery/kitchen/microwave.dm
why was it called wzhzhzh() to begin with?!
> renames wzhzhzh() to microwave_operate

- code/modules/mob/living/silicon/pai/pai.dm
when i commented out PDA code i accidentally commented out follow_pai()
please forgive me.
> Fixes pAIs

- code/game/objects/items/devices/paicard.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/silicon/pai/recruit.dm
-requesting pAIs is in 1 popup  instead of a 2 seperate pop ups now
-OOC tab as ghost "request to be pai" to get the pAI menu.
-you can still become a pAI the classic way.
tested with myself using 2 clients at the same time.
> New system for pai recruitment

- code/game/objects/items/weapons/manuals.dm
- config/config.txt
- html/changelog.html
LLA wiki added / Changelog updated.
> LLA wiki added / Changelog updated.

- code/controllers/master_controller.dm
-Added autodetection of pod location (based on the turfs it uses, /turf/simulated/shuttle being inside the engineering area)
-Added autodetection of SMES location (based on the SMES themselves being inside the engineering area)
-Added autodetection of any space tiles (based on the space turfs inside the engineering area)
-Converts the above to their individual special areas. This occurs whether or not the randomized engine is enabled.
-Allows a larger engine area to be defined, and the pod to be moved. The resulting engine will then tailor its areas to its contents.
-Pod shape must be identical to the shape at centcomm.
Tested and confirmed all areas were detected, and that the pod moved from station to transit to centcomm without issue.
> Improved Random Engine Framework

- code/modules/admin/admin.dm
- code/modules/admin/verbs/alt_check.dm
- code/modules/client/client defines.dm
- code/modules/client/client procs.dm
Multi-keys will now show up in player panel
Related accounts is now a list variable
> Improved the multi-key check

- code/datums/diseases/advance/symptoms/genetics.dm
Removed the DNA Aide symptom from possible mutations in viruses.
> Removed DNA Aide.

- code/modules/clothing/glasses/hud.dm
Modified the Atmos HUD action button slightly so it only displays when HUD is equipped to the eyes slot.
> Tweaked Atmos HUD action button

- _maps/map_files/tgstation.2.1.3.dmm
- code/game/machinery/requests_console.dm
Fixes formatting on EXTREME PRIORITY messages
Adds a security request console in the security office since that wasn't
there already.
> Fixes Requests consoles

- code/modules/clothing/glasses/hud.dm
- code/modules/telesci/telesci_computer.dm
-Redefined the Destroy proc to handle removing the images before deletion
-Added some more comments
> Fixed "That bug that occurs when Flavo deletes the HUD off someone's Face"

- code/defines/obj/weapon.dm
Adds missing research levels to debug research item
What was missing: engineering and plasmatech
> Adds missing research levels to debug research item

- code/modules/clothing/glasses/glasses.dm
Fixs green glasses broken icon
> Fixs green glasses broken icon

- code/game/machinery/vending.dm
These were already in the game but not available to get in-game without some RNG luck on "surplus clothing" crate.
> Adds khakis, maid outfit, trackpants to the clothing vendor

- code/game/objects/items/devices/Thinktronic/thinktronic.dm
- code/game/objects/items/weapons/storage/lockbox.dm
- code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
- code/game/objects/structures/extinguisher.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/suits/labcoat.dm
- code/modules/clothing/suits/wintercoats.dm
- code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
- html/changelog.html
Adds checks to make sure alt clicks cant be used while dead
changelog
> Adds checks to make sure alt clicks cant be used while dead

- code/game/objects/structures/mirror.dm
Before:
You could change your hair and facial hair with mirrors
After:
You can change your hair, facial hair, and hair color using mirrors.
> Adds Hair color option to mirrors

- code/modules/hydroponics/grown.dm
- code/modules/reagents/Chemistry-Recipes.dm
Allows uranium, gold, and silver to go from liquid to solids. 
Replaced frost oil with clonexadone. Nobody got time to mutate all the species needed to get these chemicals.
Added silver to moonflowers from hydroponics. The three minerals can be harvested from botany.
> Mineral solidification changes

- code/game/machinery/computer/medical.dm
- code/game/machinery/computer/security.dm
adds sanitize to text inputs for both consoles.
> fixes the href exploits of security and medical record consoles.

- code/controllers/configuration.dm
- code/modules/mob/mob.dm
- config/config.txt
Adds config option to enable external changelogs, comment to disable
> Adds changelog button to redirect to forum's changelog section

- code/controllers/configuration.dm
- code/game/verbs/who.dm
- config/config.txt
> Players who press adminwho with no visible admins get a link to incident reports

- code/modules/events/ninja.dm
Removes RP objective
Changes objective/steal/special to objective/steal
Thread: http://www.llagaming.net/forums/threads/ninja-v3-fix-objectives.4240/
Also adds the RP fluff to the memory as Cactus suggested.
> Fix ninja objectives

- code/modules/perseus/vending.dm
Puts a knife in the perc chef vendor
... I dont know why this is a PR, just a formality i guess.
> Let them eat cake

- code/game/gamemodes/cult/cult.dm
- code/game/gamemodes/malfunction/malfunction.dm
- code/game/gamemodes/nuclear/nuclear.dm
- code/game/gamemodes/revolution/revolution.dm
- code/game/gamemodes/wizard/wizard.dm
Cult, Malf, Nuke Ops, Revolution, and Wizard now require 18 players instead of 20
> Lowers gamemode player limit from 20 to 18

- code/game/objects/items/devices/paicard.dm
- code/modules/mob/living/silicon/pai/hud.dm
- code/modules/mob/living/silicon/pai/life.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/pai/software.dm
you can now emag a pai
also fixes being able to beat pAIs or click on them
completes #346
> Adds thermal vision to emagged PAIs

- code/game/machinery/washing_machine.dm
Revisions made to correct a series of runtime errors due to improper type checking.
> Revised the washing machine

- code/game/objects/items/weapons/tanks/watertank.dm
> fixes watertank nozzle remaining on belt after tank is dropped.

- code/modules/mob/living/carbon/human/zombie.dm
- code/modules/surgery/appendectomy.dm
Merging fixes for z_virus and appendectomy issues.
> Zombies lag fix

- code/datums/diseases/advance/advance.dm
- code/datums/diseases/advance/symptoms/emp.dm
- code/datums/diseases/advance/symptoms/symptoms.dm
Stops symptoms from activating if the infected mob is dead.
> Symptom activation fix

- code/ATMOSPHERICS/atmospherics.dm
- Added a log of renaming pipes to track abuse.
> Added Admin logging for pipe rename

- code/game/gamemodes/changeling/changeling.dm
- code/game/gamemodes/changeling/traitor_chan.dm
- code/game/gamemodes/traitor/traitor.dm
www.llagaming.net/forums/threads/traitor-scaling-rework-it-again.4911/
> Makes it so antags cannot outnumber the crew.

- code/modules/mob/living/say.dm
- code/modules/mob/mob_helpers.dm
- code/modules/reagents/Chemistry-Readme.dm
- code/modules/reagents/Chemistry-Reagents.dm
-spacedrugs and sleeptoxin will alter text "to.. look a bit.. more like... this"
-mindbreaker and cryptobiolin will alter text to stutter
> Adds speech altering to reagents

- code/modules/events/mass_hallucination.dm
- tgstation.dme
Requested from: www.llagaming.net/forums/threads/remove-random-hallucinations.4937/
-Removes Mass Hallucination event
> Removes Mass Halluciation

- code/game/gamemodes/blob/blobs/shield.dm
Makes the shield blob work like it was intended. Blocks air flow and temperature.
> Shield blob fix

- code/game/machinery/kitchen/microwave.dm
Makes additional human burgers display the right name instead of "-burger".
> Human burger fix

- code/game/gamemodes/blob/blob.dm
- code/game/gamemodes/changeling/changeling.dm
- code/game/gamemodes/cult/cult.dm
- code/game/gamemodes/game_mode.dm
- code/game/gamemodes/malfunction/malfunction.dm
- code/game/gamemodes/nuclear/nuclear.dm
- code/game/gamemodes/revolution/revolution.dm
- code/game/gamemodes/traitor/double_agents.dm
- code/game/gamemodes/wizard/wizard.dm
- code/game/gameticker.dm
- code/game/jobs/job_controller.dm
-adds required jobs for gamemodes under there recommended player count
-All jobs are decided BEFORE gamemodes
http://www.llagaming.net/forums/threads/minimum-gamemodes-fun-edition.5001/
> Changes to gamemode minimum mode

- code/datums/wires/telepad.dm
- code/modules/telesci/telepad.dm
- code/modules/telesci/telesci_computer.dm
- tgstation.dme
Adds wires to telepads for remote control (or sabotage).
> Adds wires to telepads

- code/game/machinery/turrets.dm
Note: I hate construction code.
> Make turrets fixable

- code/modules/assembly/heartmonitor.dm
- code/modules/assembly/helpers.dm
- code/modules/assembly/infrared.dm
- code/modules/assembly/signaler.dm
Fixes null.density runtime from infrared.
Fixes null.key runtime from heartmonitor-signaler assemblies.
Adds ismonitor() to helpers.dm
Adds better logging to signaler logs.
> Fixes some assembly runtimes

- code/game/gamemodes/traitor/double_agents.dm
- code/game/objects/items/devices/tablets/tablets.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/simple_animal/borer/borer_egg.dm
-fixes borer egg
-fixes ghosts having opacity while invisible
-adds station_name to tablets because byond removed it from the title bar
> fixes double agents maybe hopefully

- code/modules/telesci/telepad.dm
> Fix telepad not deleting correctly when deconstructing it

- code/modules/admin/verbs/deadsay.dm
> adds weeman

- interface/interface.dm
- interface/skin.dmf
Adds "Me" to hotkeys as key: Y
> Adds "Me" to hotkeys as key: Y

- code/modules/mob/living/carbon/human/npc/zombie.dm
Fixed borers getting teleported into nothingness when their host zombifies.
Fixed Zombify() turning mutantrace humans back to normal humans.
Fixed contents not transfering correctly.
Changed "zombie/O" to "zombie/Z".
Moved "You feel the life slowly slip away from you as you join the army of the undead.." from the virus to the Zombify() proc incase an evil borer controls its host when it zombifies.
> Some zombie fixes

- code/game/objects/items/devices/paicard.dm
- code/game/objects/items/devices/tablets/tablets.dm
This is standalone and won't effect the other changes I will make to the rest of the pAI software menu.
As for my next PR, I plan on changing things about pAIs, so it won't be just visual
> pAI object visual overhaul

- code/game/objects/items/devices/tablets/data.dm
- code/game/objects/items/devices/tablets/laptops.dm
- code/game/objects/items/devices/tablets/programs/nanonet.dm
- code/game/objects/items/devices/tablets/programs/toggleutilities/camera.dm
- code/game/objects/items/devices/tablets/server.dm
- code/game/objects/items/devices/tablets/tablets.dm
- code/modules/admin/admin.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/topic.dm
- tgstation.dme
http://www.llagaming.net/forums/threads/nanonet-social-media.5150/
> NanoNet Social Media App

- code/datums/spells/mind_transfer.dm
- code/modules/mob/living/simple_animal/borer/borer.dm
- code/modules/mob/login.dm
*Should* fix update_login_details logging a multikey warning when a borer assumes control of a braindead person.
> Borer multikey fix

- code/datums/mind.dm
- code/modules/mob/living/simple_animal/borer/borer_verbs.dm
Allows admins to make borers good/evil with the traitor panel.
> Adds borers to the traitorpanel

- code/game/turfs/turf.dm
> fixes space pull

- code/controllers/ProcessScheduler/processes/disease.dm
- code/controllers/ProcessScheduler/processes/lighting.dm
- code/controllers/ProcessScheduler/processes/machines.dm
- code/controllers/ProcessScheduler/processes/mob.dm
- code/controllers/ProcessScheduler/processes/npc.dm
- code/controllers/ProcessScheduler/processes/objects.dm
- code/controllers/ProcessScheduler/processes/pipenets.dm
- code/controllers/ProcessScheduler/processes/powernets.dm
while loops instead of for loops. less istype() thrown around.
> Refactors processing loops

- code/game/objects/items/devices/paicard.dm
- code/game/objects/items/devices/tablets/tablets.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/pai/software_new.dm
- tgstation.dme
This causes people playing as pAI to be greeted with lovely looking
screens rather than the old, ugly one.
> pAI Visual Overhaul (Mostly Visual, some functionality)

- code/modules/mob/living/living.dm
-Adds Give Command to "IC" tab. Give items to any mob
-When removing something from a mob's hands, you will equip it to your own hands
http://www.llagaming.net/forums/threads/taking-giving-items-to-handslot.5250/
> Hand Strip Panel Changes / Give Command

- code/modules/virtual_reality/controller.dm
Completes the virtual headset drache started back when VR was new
> Completes the virtual headset drache started back when VR was new

- code/modules/mob/living/simple_animal/borer/borer_upgrades.dm
- code/modules/mob/living/simple_animal/borer/borer_verbs.dm
- code/modules/mob/living/simple_animal/borer/say.dm
Fixes borers not being able to buy Coagulation Agent upgrade.
Fixes borers not being able to use Telepathic Projection while inside a host.
"Fixes" . triggering hivemind (since some people like to start their sentences with ...).
> Small borer bug fixes

- code/modules/virtual_reality/controller.dm
fixes VR headset check when people are inside lockers.
> Small bug fix

- .travis.yml
- code/__HELPERS/text.dm
- code/controllers/supply_shuttle.dm
Makes the code compile on byond 510.1328
updates travis.yml
> Makes the code compile on byond 510.1328

- code/modules/admin/mentor.dm
- interface/skin.dmf
Same code, already tested by Batts, Drache and I as per Raptorblaze's
request.
> Adds Mentorhelp tab

- code/_onclick/hud/hud.dm
- code/game/objects/items/devices/flashlight.dm
- code/modules/admin/admin_verbs.dm
- code/modules/events/task/task_event.dm
- code/modules/lighting/lighting_atom.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/silicon/ai/freelook/eye.dm
- code/modules/mob/living/simple_animal/honking_angel.dm
- code/modules/power/lighting.dm
- code/modules/space_exploration/templates/template.dm
Adds range to lighting
Fixes honking angels having been accidentally reverted
Removes AI camera accel (temp)
Fixes blindness not working on certain items
Fixes lights not deleting on destroy()
Fixes task events
Fixes Readmin self
Removes color from flashlights
Fixes stamina not hiding on hud
> June fixes
