LLA-Gaming/SS13

code/_onclick/item_attack.dm
code/modules/mob/living/carbon/human/death.dm
code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/mob/living/carbon/human/human_damage.dm
code/modules/mob/living/living_defense.dm

Implemented Melee weapon damage and remaining HP logs
Implemented Thrown weapon damage and remaining HP logs
Implemented Punch damage and remaining HP logs
Implemented logging when critical is entered or left by a human
Implemented logging when a human dies
Made Remaining HP display as "DEAD" in attack logs when mob is dead to hide confusing unnecessary readings

Expanded Attack, Crit, and Death Logging

---

code/game/mecha/equipment/weapons/weapons.dm
code/modules/projectiles/projectile.dm

Follow up to PR #158 
Implemented damage and REMHP logging to the guns.
Had to add it separately for the mech heavy pulse gun.
Tested and found no issues. At worst, its possible a projectile overwrites the bump proc and will require manual addition of the logs, but I did not see any besides the heavy pulse that did so and dealt damage.

Projectile Logging

---

code/modules/client/client procs.dm
code/modules/mob/living/carbon/human/human_attackhand.dm

-Changed href log timestamps to include seconds and use the standard proc.
-Fixed the CPR logs being backwards (the target was being logged as having CPR'd the person who was doing the CPR)
Tested and confirmed both worked as expected.

CPR Log Fix and href Timestamp Improvement

---

code/modules/mob/living/carbon/metroid/metroid.dm

Explicitly defined the alloweat var for the golem mask so that they can eat food.

Fix Golems Eating

---

code/game/machinery/doors/airlock.dm
html/changelog.html

The issue was that the autoclose() proc was being called too quickly to
actually close the door
additionally i setup a if statement in the autoclose proc (Where it
checks if a human is there) that if the timing is hacked it would close
faster. tested and people walking through doors can still make it
through before the doors close quickly. tested while running too, works
fine.

Fixed airlocks not closing correctly with hacked timing

---

code/game/objects/items/devices/Thinktronic/Laptop.dm

They aren't really used and clutter up the messenger list

TWEAK: Disable messenger on round start laptops.

---

code/datums/diseases/dna_spread.dm

cure was defined twice and cure_id was not defined.

Fixed retrovirus being uncurable

---

code/ATMOSPHERICS/pipes.dm
code/controllers/configuration.dm
code/controllers/master_controller.dm
code/game/area/Space Station 13 areas.dm
config/game_options.txt

- New defined areas to support defining as many template engines as desired
- Config option "randomize_engine_template" must be inserted into game_options.txt to enable the framework (only do this if at least 1 template is defined)
- Each new template will require its own child area of /engine/alternate/
- The "default" engine will always be whatever is already on the station map. Templates overwrite this if used.
- Each template must contain 100% of what should be in main engineering and the shape of all templates must match the engineering area.
- Any unused templates are erased during setup, even if the option is disabled. This reduces lag during game and prevents accidental spawning on them.

Implemented Multi-Engine Framework

---

code/game/area/Space Station 13 areas.dm

Apparently my original fix didn't resolve it reliably. Switched the proc to use safepick() and added a check for null return. Tested and the runtime error no longer occurs.
Was symptomless, but better safe than sorry.

Runtime Error Patched

---

code/game/gamemodes/cult/ritual.dm
code/game/gamemodes/cult/runes.dm
code/modules/reagents/Chemistry-Reagents.dm

1) Reduced the numbers required to convert crew members from 3 to 2.
2) Wine deconverts in the same way and quantity as holy water.
3) Wine can be cleansed from body (and converted to unholy water) by cultists in the same way as holy water.

Cult Balancing

---

code/datums/supplypacks.dm
code/modules/reagents/reagent_containers/food/snacks.dm
html/changelog.html

Cargo can now order wood(30 sheets) and carpet(50 sheets) as well as ordering a Pizza Delivery

Pizza, Carpet, and Wood added to cargo ordering

---

code/game/machinery/machinery.dm

adds a canUseTopic() proc to humanoids, but put a clause it only allow
it to be used on humans and not computers

Allow Xenos to strip humans

---

code/game/objects/items/weapons/grenades/grenade.dm

the numbers were written as strings.

Fixed being unable to edit a grenades timer with a screwdriver

---

code/game/objects/items/weapons/grenades/flashbang.dm

Included security berets in flashang's ear_safety check, so they protect against its bang.

Security berets ear_safety

---

code/game/verbs/who.dm
code/modules/admin/admin_verbs.dm

-If "Hide admin messages" is on, the who verb will return the list of
players + number of players rather then antag status and whos dead or
not
-Getmob, PM mob, and Show player panel added to "Hide Most" list. you
can still do these things they just wont show up in right click or
object tab.

Admin stuff

---

code/modules/mob/mob.dm

Stops people from being anchored when they aren't buckled to a object.
additionally.. fixes indention issues

Fixs swivel chair exploit

---

code/modules/events/immovable_rod.dm

Tested by launching 30+ immovable rods at the station, no crash

Fixed the crash with immovable rods

---

code/modules/events/anomaly_bluespace.dm

Bug: Bluespace Anomaly occurs even after the anomaly is gone
Fix: Corrected indentation to bring end() in line with other anomalies.

Fixed Bluespace Anomaly Event

---

code/game/objects/items/robot/robot_upgrades.dm

Fix for #250
Mining cyborg jetpack is now properly stored in the contents of the
cyborg module like all the other cyborg module items.
Previously failed a check done in /code/game/objects/items.dm in the
attack_ai() proc.
Problem found, traced, fixed, and tested.

Mining Cyborg Jetpack Fix

---

code/modules/reagents/reagent_containers/borghydro.dm

Medical Cyborg gets dexalin, kelotane, bicaridine, antitox, inaprovaline and tricordrazine in its hypospray, instead of doc's delight, inaprovaline and spaceacillin.

Medborg hypospray's reagents change

---

code/modules/admin/ahelp_panel.dm
config/dbconfig.txt

Fixs runtimer error with "View Admin helps" when SQL is not enabled.
was causing problems with adimhelping/crashs on test servers.

Comments out SQL_ENABLED by default

---

code/modules/projectiles/guns/energy.dm

code taken from tgstation's fix:
The new procedure goes as follow :
the click code goes on until its end (afterattack),
if there's enough energy in the gun cell, a selected mode shot is
chambered (laser, electrode, ...),
the attack/firing code does its things,
at the end of it, we check if the shot was spent (i.e the actual
"bullet" was send). If so, we draw on the gun cell the correct amount of
power. If not, we just discard the chambered shot.

Fixes Energy based guns using charge without being fired

---

code/modules/admin/banjob.dm

Our server uses the GUEST_JOBBAN config option but it doesnt actually
work. this is because the check for guests and guest job bans were
commented out.
tested the following:
-Guests cannot play as head/sec/AI roles
-Was able to play as these roles by using an account
-Did not break job bans. could sill apply them.

Fixs guest job bans

---

code/game/objects/items/weapons/storage/backpack.dm
code/modules/admin/admin.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/verbs/adminsay.dm
code/modules/admin/verbs/randomverbs.dm
code/modules/power/gravitygenerator.dm

-admin message when someone shuts off the GravGen
-Fixs a backpack's incorrect name
-Asay will now always be enabled despite admin messages being turned
off. deadmin if you dont wish to see asay

Admin verb to re-enable the gravgen.

---

code/game/objects/structures/crates_lockers/closets/secure/security.dm
code/game/objects/structures/crates_lockers/closets/wardrobe.dm

Image: http://i.imgur.com/zlP1oTH.png
Security has these very nice dress shirt and blue pants alt. uniforms. Previously, they were only available by ordering them from Cargo. Now they spawn in HoS/Warden lockers, Security lockers, and Sec Wardrobes
Note that the relevant jackets were *not* included in these lockers; The jackets are unarmored and cannot hold gear on the suit storage, so I assumed nobody would want them.
Also note that the probability checks for Camopants/Mil.Jacket in Security Wardrobes have been removed; They will now always have one of each, with a 30% chance for another. Nobody's ~*style*~ should be left in the hands of an RNG

Adds fancy dress blues to Security

---

code/game/verbs/ooc.dm

"Show/Hide OOC" command will only mute OOC locally in the all tab, OOC will still show up in OOC tab
Before:
Show/Hide command would hide OOC completely regardless of tab
After
Show/Hide command would hide OOC in the all tab, if they want to view OOC they can swap to the OOC tab.

"Show/Hide OOC" command tweak

---

code/game/objects/items/weapons/manuals.dm
config/config.txt

until another wiki becomes available, the current wiki is gone and the ss13.eu wiki is full of ads.

Temporary wiki change to tgstation13.org

---

code/game/machinery/doors/airlock.dm

Buffs airlock security
Security, High Security, Command, and Vault airlock will always have randomized wires as where the other airlocks share the same wires.

Randomizes Security, High Security, Command, and Vault airlock wires

---

code/game/gamemodes/game_mode.dm
code/game/gamemodes/nuclear/nuclear.dm

Currently where it stands "fun" round types need at least 18 players ready to start generally the server has say maybe 24-30 people on and half of them do not ready up for various reasons.. which i understand. They could want to late join, ive noticed late joining is very popular, more of a choice on what job you can take, indecisive abotu what job you want.
The change i propose would be for the round types to be determined by how many players are on and in the lobby, ready or not. observers would not count. Say there are 25 players on and only 5 ready up and nuke ops is chosen, there would be 5 nuke ops and no station crew and likely a quick round, but that means there are 20 players in the lobby who will likely late join after the round starts. say there are 25 players on and only 5 in …

Round Types Pooling Change

---

code/modules/mob/living/carbon/human/zombie.dm
code/modules/surgery/appendectomy.dm

Changed Z_virus's stage_act() logic to prevent processing of disease stages if the user is already a zombie. Hopefully resolves massive lag caused by zombies.

Z_virus optimization (To fix the lag)

---

code/game/machinery/door_control.dm
code/game/objects/items/devices/lightreplacer.dm
code/modules/clothing/glasses/glasses.dm
code/modules/clothing/head/jobs.dm

- Added on/off toggle for Night Vision Goggles, also added action button which can be used to toggle them while worn.
- Added obj/machinery/door_control/closer which functions identically to a normal button except it can only close.
- Added the ability to add bulbs to a light replacer by clicking the replacer with the box in the active hand. Adds 5 at a time.
- Made a child of det_hat which uses the grey detective hat icon instead of the brown one.

Implemented Sneaky's Suggestions

---

code/modules/clothing/glasses/hud.dm

-Added a variable to tune how far out the HUD looks to preload HUD icons.
-HUDs will preload 16 tiles out from user, but only tiles in view (not obstructed). This will reduce HUD gaps which appear when moving significantly.

Added Pre-loading to HUD glasses

---

code/controllers/configuration.dm
code/game/gamemodes/changeling/changeling.dm
code/game/gamemodes/traitor/traitor.dm
config/game_options.txt

sets a minimum to traitor and changeling when antag scaling is enabled.
http://www.llagaming.net/forums/threads/old-sorta-new-traitor-scaling.4823/

Old (Sorta New) Antag Scaling

---

code/game/objects/items/weapons/melee/energy.dm
code/game/objects/items/weapons/twohanded.dm

Changes energy-based melee weapons to do burn damage in their active state.
Removes bleeding from energy-based melee weapons.
Changed src.loc's in twohanded.dm to get_turf(src).
Forum post: http://www.llagaming.net/forums/threads/energy-based-melee-weapons-do-burn-damage.4862/

Changes energy-based melee weapons to do burn damage

---

code/datums/diseases/advance/symptoms/emp.dm

Prevents dead infected mobs from becoming EMP generators.

EMP symptom fix

---

code/ATMOSPHERICS/atmospherics.dm
code/ATMOSPHERICS/datum_pipeline.dm

-Adds ability to rename whole pipelines with the pen
-Adds ability to rename components individually
-Leaving the field blank will result in reversion to the default names for each pipe.
-Pipeline names will persist for all new pipes added to that pipeline after renaming.
Please keep an eye out for abuse. I have a couple ideas in mind to balance out potential abuses...

Implemented pipe and pipeline renaming

---

html/changelog.html

-For faster on the fly adding, a link to all coders/spriters/contributers was added in place of Coders/Spriters.
-Adds hippiestation to the thanks because we've ported stuff from there
-**UPDATES BROKEN LINKS**

Updates the changelog to include credits

---

code/controllers/voting.dm
code/game/gameticker.dm
code/modules/mob/death.dm
code/modules/mob/login.dm
code/modules/mob/logout.dm

When there are no living players in the game world, crew transfer votes will instantly happen instead of waiting 10 minutes

Instant crew transfer when there are 0 living players

---

code/modules/mob/living/simple_animal/hostile/eye_horror.dm

-Added hallucination effect, base rate of hallucination gain is 2x human hallucination loss.
-Only hits "hearers" in range, base range 7
-Hallucination strength multiplies with victim count
-Hallucination range scales with additional victims

Implemented Hallucination effect for Eyehorror

---

html/create_object.html

Changes the logic on the create object panel to use a search button instead of every typed letter. This prevents the freezing from occurring unless the search field is blank. Javascript by Falaskian.
Tested and confirmed.

Replace Create Object panel filtering logic

---

code/ATMOSPHERICS/components/portables_connector.dm
code/LINDA/LINDA_fire.dm
code/LINDA/LINDA_system.dm
code/LINDA/LINDA_turf_tile.dm
code/modules/power/singularity/singularity.dm

most foreach loops in atmospheric related code has been optimized for performance.
additionally modifies a foreach loop in singularity's eat() to improve performance
also fixes runtime that would occur when singularities ate atmospheric gear

Refactors atmospheric/singularity loops

---

code/game/machinery/cryo.dm

Changes the icon handling to make the mob inside of a cryotube visible. Removes the use for the cryo-occupied icon state.

Make Mob visible in Cryo

---

code/modules/admin/player_notes.dm

Increase the specificity of the note timestamps to include the hour and minute in server time, this will allow us to locate logs much more quickly in the event of questions.

Improve specificity of note timestamp
